version: "3.7"

networks:
  main_net:
    name: main_main_net
    external: true
  back_net:
    driver: bridge

services:
  buildin-auth:
    container_name: buildin-auth
    image: implude/buildin-auth:latest
    networks:
      - main_net
      - back_net
    environment:
      - DOPPLER_TOKEN
    expose:
      - 3000
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres:alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
    restart: always
    networks:
      - back_net